version: '3'

services:
  mongodb:
    image: mongo:6-jammy
    volumes:
      - ./data:/data/db
    ports:
      - 0.0.0.0:12701:12701

  klerk:
    build: .
    volumes:
      - .env:/app/target/release/.env
      - .env:/app/.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017