version: '3'

services:
  mongodb:
    restart: always
    image: mongo:6-jammy
    volumes:
      - ./data:/data/db

  klerk:
    build: .
    restart: always
    volumes:
      - .env:/app/target/release/.env
      - .env:/app/.env
    environment:
      MONGODB_URI: mongodb://mongodb:27017
      HOST: 0.0.0.0
      PORT: 12701
    ports:
      - 0.0.0.0:12701:12701